spring:
  # =============================
  # APPLICATION NAME
  # =============================
  application:
    name: Customer-Rest
  # =============================
  # DATASOURCE CONFIG
  # =============================
  data:
    jpa:
      repositories:
        enabled: false
    # =============================
    # REST DATA CONFIG
    # =============================
    rest:
      base-path: /api
  datasource:
    url: jdbc:postgresql://localhost:5432/cocus?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: postgres
    password: Cocus@PT541_D@ata
    hikari:
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      # =======================================================================
      # AUTO UPDATE DATABASE SCHEMA (Not Recommended In Production Environment)
      # =======================================================================
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: false

# =============================
# SERVER CONFIG
# =============================
server.port: 8081

# =============================
# WEB SERVICES URIs
# =============================
com:
  cocus:
    label:
      uri: http://localhost:8082

# =============================
# KEYCLOAK
# =============================
keycloak:
  realm: cocus
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: cocusclient
  credentials:
    secret: 70702f9b-e348-4005-ab59-ec17fafb1945
  bearer-only: true
  security-constraints[0].authRoles[0]: cocus-role
  security-constraints[0].securityCollections[0].patterns[0]: /api/*

# =============================
# LOGGING CONFIG
# =============================
logging:
  level:
    org.keycloak: TRACE